### ISSUE TITLE
 无法更新快递信息

### ISSUE THREAD

**Issue by hyc1743** [junyilou/junyilou.github.io#1]
ifttt快递通知每次都只能收到第一条消息而不会再次推送，我在VPS上运行的py脚本

**Comment by hyc1743** [comment]
关闭终端后就收不到推送，可否使用
nohup python -u Kuaidi_IFTTT.py xxxxx > log.out 2>&1 &
来执行？

**Comment by junyilou** [comment]
IFTTT Activity 中有没有看到除了第一条物流意外的推送记录？或者在程序执行时有没有 wget 向 maker.ifttt.com 推送的显示？

**Comment by junyilou** [comment]
哦等一下，你说关闭终端？我设计的是要将这个东西在 screen 里面运行。我没有做计划任务那边的考虑就直接用 time.sleep 来实现了，所以关闭终端就等于直接杀死了进程。我现在是 screen -S k 然后在其中运行，Ctrl+A 然后 D 就可以退出 screen，即可继续做其他的事情
